# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TangAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('long_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'tang_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TangShi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.CharField(max_length=1000, unique=True)),
                ('strains', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tang_shi',
                'managed': False,
            },
        ),
    ]
